general:
  project_name: neural_style_transfer
  model_type: xinet_picasso_muse
  model_path:  ../../stm32ai-modelzoo/neural_style_transfer/xinet_picasso_muse/Public_pretrainedmodel_public_dataset/coco_2017_80_classes_picasso/xinet_a75_picasso_muse_160/xinet_a75_picasso_muse_160_nomp.tflite
  display_figures: true

operation_mode: prediction

dataset:
  name: COCO

preprocessing:
  rescaling:
    scale: 1/255.0
    offset: 0
  resizing:
    interpolation: bilinear
    aspect_ratio: fit
  color_mode: rgb

postprocessing:
  bilateral_diameter: 15
  sigma_color: 20
  sigma_space: 10
  scaling_alpha: 1.25
  scaling_beta: -10
  saturation_scale: 1.2

prediction:
  test_files_path: ./datasets/coco/images

mlflow:
  uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}