general:
   model_type: heatmaps_spe # heatmaps_spe, yolo_mpe
   # path to a `.tflite` or `.onnx` file.
   model_path: ../../stm32ai-modelzoo/pose_estimation/movenet/ST_pretrainedmodel_public_dataset/custom_dataset_person_13kpts/st_movenet_lightning_heatmaps_192/st_movenet_lightning_heatmaps_192_int8_pc.tflite

operation_mode: deployment

dataset:
   class_names: [person]

preprocessing:
   resizing:
      interpolation: bilinear
      aspect_ratio: crop
   color_mode: rgb # rgb, bgr

postprocessing:
   kpts_conf_thresh: 0.15

tools:
   stedgeai:
      version: 10.2.0
      optimization: balanced
      on_cloud: False # Not Available For STM32N6
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path: ../application_code/pose_estimation/STM32N6/
   IDE: GCC
   verbosity: 1
   hardware_setup:
      serie: STM32N6
      board: STM32N6570-DK

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}

mlflow:
   uri: ./src/experiments_outputs/mlruns