general:
   model_type: deeplab_v3
   model_path: ../../stm32ai-modelzoo/semantic_segmentation/deeplab_v3/ST_pretrainedmodel_public_dataset/person_coco_2017_pascal_voc_2012/deeplab_v3_mobilenetv2_05_16_256/deeplab_v3_mobilenetv2_05_16_256_asppv2.h5
operation_mode: chain_qd

dataset:
   name: pascal_voc_person
   class_names: ['background','person']
   quantization_path: ./datasets/pascal_voc_person/JPEGImages
   quantization_masks_path: ./datasets/pascal_voc_person/SegmentationClassAug
   quantization_files_path: ./datasets/pascal_voc_person/ImageSets/Segmentation/quantization.txt #or train.txt with the quantization_split

preprocessing:
  rescaling: {scale: 1/127.5, offset: -1}
  resizing:
    aspect_ratio: crop
    interpolation: nearest
  color_mode: rgb

quantization:
  quantizer: onnx_quantizer
  quantization_type: PTQ
  quantization_input_type: float
  quantization_output_type: float
  granularity: per_channel   # per_tensor
  optimize: False   # can be True if per_tensor
  export_dir: quantized_models

tools:
   stedgeai:
      version: 10.2.0
      optimization: balanced
      on_cloud: False
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path: ../application_code/semantic_segmentation/STM32N6/
   IDE: GCC
   verbosity: 1
   hardware_setup:
      serie: STM32N6
      board: STM32N6570-DK #STM32H747I-DISCO, STM32N6570-DK

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}